# Generated by Django 2.1.5 on 2020-01-13 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='type_name',
            new_name='blog_type',
        ),
    ]
