# Generated by Django 2.1.5 on 2020-02-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_root'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_time']},
        ),
    ]
